### ISSUE TITLE
Add X/Y/Z display to movement screen

### ISSUE THREAD

**Issue by jim-thompson** [re3Dprinting/touchscreen#55] opened 2020-02-20 15:39 UTC
No way to tell what the coordinates of the print head(s) are without a display.

**Comment by chief-hacker** [comment] 2020-02-23 19:59
Is this a duplicate of issue #34?

**Comment by plloppii** [comment] 2020-07-11 16:30
Fixed as of main/merge-ui-update

**Closed by plloppii** 2020-07-11 16:30 UTC
Labels: DEFCON 1, enhancement
